languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Vedant Tekale"
# logo = "img/logo.png"
description = "Welcome To My Web Site"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Vedant Tekale"
  image = "img/avatar.png"
  headline = "This is my portfolio website"
  bio = "I am a passionate cyber security enthusiast "
   links = [
     { link = "https://vedanttekale20.github.io/welcome/" },
     { github = "https://github.com/Vedanttekale20/" },
     { x-twitter = "https://twitter.com/_justynot" }
   ]
